var languages = [
  {"name": "Afrikaans", "code": "afr", "native": "Afrikaans"},
  {"name": "Albanian", "code": "sqi", "native": "Shqip"},
  {"name": "Arabic", "code": "ara", "native": "العربية"},
  {"name": "Armenian", "code": "hye", "native": "Հայերեն"},
  {"name": "Azerbaijani", "code": "aze", "native": "Azərbaycan dili"},
  {"name": "Basque", "code": "eus", "native": "Euskara"},
  {"name": "Belarusian", "code": "bel", "native": "Беларуская"},
  {"name": "Bosnian", "code": "bos", "native": "Bosanski"},
  {"name": "Bulgarian", "code": "bul", "native": "Български"},
  {"name": "Catalan", "code": "cat", "native": "Català"},
  {"name": "Chinese", "code": "zho", "native": "中文"},
  {"name": "Croatian", "code": "hrv", "native": "Hrvatski"},
  {"name": "Czech", "code": "ces", "native": "Čeština"},
  {"name": "Danish", "code": "dan", "native": "Dansk"},
  {"name": "Dutch", "code": "nld", "native": "Nederlands"},
  {"name": "English", "code": "eng", "native": "English"},
  {"name": "Fijian", "code": "fij", "native": "Na Vosa Vakaviti"},
  {"name": "Finnish", "code": "fin", "native": "Suomi"},
  {"name": "French", "code": "fra", "native": "Français"},
  {"name": "Galician", "code": "glg", "native": "Galego"},
  {"name": "Georgian", "code": "kat", "native": "ქართული"},
  {"name": "German", "code": "deu", "native": "Deutsch"},
  {"name": "Greek", "code": "ell", "native": "Ελληνικά"},
  {"name": "Haitian", "code": "hat", "native": "Kreyòl Ayisyen"},
  {"name": "Hebrew", "code": "heb", "native": "עברית"},
  {"name": "Hindi", "code": "hin", "native": "हिन्दी"},
  {"name": "Hungarian", "code": "hun", "native": "Magyar"},
  {"name": "Icelandic", "code": "isl", "native": "Íslenska"},
  {"name": "Indonesian", "code": "ind", "native": "Bahasa Indonesia"},
  {"name": "Italian", "code": "ita", "native": "Italiano"},
  {"name": "Japanese", "code": "jpn", "native": "日本語"},
  {"name": "Korean", "code": "kor", "native": "한국어"},
  {"name": "Latvian", "code": "lav", "native": "Latviešu"},
  {"name": "Lithuanian", "code": "lit", "native": "Lietuvių"},
  {"name": "Luxembourgish", "code": "ltz", "native": "Lëtzebuergesch"},
  {"name": "Macedonian", "code": "mkd", "native": "Македонски"},
  {"name": "Malay", "code": "msa", "native": "Bahasa Melayu"},
  {"name": "Mongolian", "code": "mon", "native": "Монгол хэл"},
  {"name": "Nepali", "code": "nep", "native": "नेपाली"},
  {"name": "Norwegian", "code": "nor", "native": "Norsk"},
  {"name": "Persian", "code": "fas", "native": "فارسی"},
  {"name": "Polish", "code": "pol", "native": "Polski"},
  {"name": "Portuguese", "code": "por", "native": "Português"},
  {"name": "Romanian", "code": "ron", "native": "Română"},
  {"name": "Russian", "code": "rus", "native": "Русский"},
  {"name": "Serbian", "code": "srp", "native": "Српски"},
  {"name": "Slovak", "code": "slk", "native": "Slovenčina"},
  {"name": "Slovenian", "code": "slv", "native": "Slovenščina"},
  {"name": "Spanish", "code": "spa", "native": "Español"},
  {"name": "Swedish", "code": "swe", "native": "Svenska"},
  {"name": "Thai", "code": "tha", "native": "ไทย"},
  {"name": "Tibetan", "code": "bod", "native": "བོད་སྐད་"},
  {"name": "Turkish", "code": "tur", "native": "Türkçe"},
  {"name": "Ukrainian", "code": "ukr", "native": "Українська"},
  {"name": "Uzbek", "code": "uzb", "native": "Oʻzbekcha"},
  {"name": "Vietnamese", "code": "vie", "native": "Tiếng Việt"},
  {"name": "Welsh", "code": "cym", "native": "Cymraeg"},
  {"name": "Yiddish", "code": "yid", "native": "ייִדיש"}
];